// Generated by tool/gen_push_i18n.dart — do not edit manually.
// Re-run after adding/changing suggestions.*.title keys in lib/i18n/*.i18n.json.

const kTitles: Record<string, Record<string, string>> = {
  en: {},
  sl: {},
  de: {},
};

const kFallbackTitle: Record<string, string> = {
  en: 'Your garden needs attention',
  sl: 'Vaš vrt čaka na vas',
  de: 'Ihr Garten braucht Aufmerksamkeit',
};

const kFallbackBody: Record<string, string> = {
  en: "Tap to see today's suggestion",
  sl: 'Tapnite za predlog dneva',
  de: 'Tippen für den heutigen Vorschlag',
};

function norm(lang: string | null | undefined): string {
  return lang === 'sl' || lang === 'de' ? lang : 'en';
}

export function pushTitle(messageKey: string, lang: string | null | undefined): string {
  const l = norm(lang);
  return kTitles[l][messageKey] ?? kFallbackTitle[l];
}

export function pushBody(lang: string | null | undefined): string {
  return kFallbackBody[norm(lang)];
}
