// Generates supabase/seed/plant_task_rules.sql from the single source of truth
// (lib/data/seed/plant_task_rules_seed.dart) so the cloud rules never diverge
// from the app's bundled seed. Idempotent upsert (on conflict ... do update) —
// safe to re-run after the seed grows/changes. Run: dart run tool/gen_rules_sql.dart
//
// Rule ids are stable slugs, add-only — see CLAUDE.md (catalog id contract).
import 'dart:io';

import 'package:tendask/data/seed/plant_task_rules_seed.dart';

String _q(String s) => "'${s.replaceAll("'", "''")}'";
String _qOrNull(String? s) => s == null ? 'null' : _q(s);

void main() {
  final out = File('supabase/seed/plant_task_rules.sql')
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(buildRulesSql());
  stdout.writeln(
    'Wrote ${out.path}: ${PlantTaskRulesSeed.rules.length} plant_task_rule rows.',
  );
}

/// Builds the rules SQL from the seed. Pure (no I/O) so a test can assert the
/// committed plant_task_rules.sql still matches the seed.
String buildRulesSql() {
  final b = StringBuffer()
    ..writeln('-- GENERATED by tool/gen_rules_sql.dart — DO NOT EDIT BY HAND.')
    ..writeln('-- Source of truth: lib/data/seed/plant_task_rules_seed.dart')
    ..writeln('-- Idempotent: re-run after seed changes, then apply to the cloud.')
    ..writeln();

  for (final r in PlantTaskRulesSeed.rules) {
    // "window" is a reserved word in Postgres — must stay quoted.
    b.writeln(
      'insert into plant_task_rule '
      '(id, scope, ref_id, task_type_id, timing_anchor, "window", cadence, '
      'frost_gate, weather_guard, source_ref, confidence, message_key) values ('
      '${_q(r.id)}, ${_q(r.scope)}, ${_q(r.refId)}, ${_q(r.taskTypeId)}, '
      '${_q(r.timingAnchor)}, ${_q(r.window)}::jsonb, ${_qOrNull(r.cadence)}, '
      '${r.frostGate}, ${_qOrNull(r.weatherGuard)}, ${_q(r.sourceRef)}, '
      '${_q(r.confidence)}, ${_q(r.messageKey)}) '
      'on conflict (id) do update set '
      'scope = excluded.scope, ref_id = excluded.ref_id, '
      'task_type_id = excluded.task_type_id, '
      'timing_anchor = excluded.timing_anchor, "window" = excluded."window", '
      'cadence = excluded.cadence, frost_gate = excluded.frost_gate, '
      'weather_guard = excluded.weather_guard, '
      'source_ref = excluded.source_ref, confidence = excluded.confidence, '
      'message_key = excluded.message_key;',
    );
  }

  return b.toString();
}
