// Generates supabase/functions/smart-engine/testdata/catalog_fixture.ts from the
// same Dart seeds that produce the cloud SQL, so the engine's season simulation
// measures the RULES WE SHIP instead of a hand-written stand-in that quietly
// drifts. A TS module (not JSON) on purpose: `deno test` runs without
// --allow-read on CI, and an import is type-checked, so a shape change breaks
// the build instead of the measurement.
//
// Only the columns the engine actually reads are emitted — the fixture ships
// inside the deployed function directory, and source_ref/cadence/confidence have
// no reader there. Run: dart run tool/gen_engine_fixture.dart
import 'dart:convert';
import 'dart:io';

import 'package:tendask/data/seed/catalog_seed.dart';
import 'package:tendask/data/seed/plant_task_rules_seed.dart';

String _s(String v) => jsonEncode(v);
String _sOrNull(String? v) => v == null ? 'null' : jsonEncode(v);

void main() {
  final out = File('supabase/functions/smart-engine/testdata/catalog_fixture.ts')
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(buildEngineFixture());
  stdout.writeln(
    'Wrote ${out.path}: ${CatalogSeed.taskTypes.length} task_type, '
    '${PlantTaskRulesSeed.rules.length} plant_task_rule rows.',
  );
}

/// Builds the fixture module. Pure (no I/O) so a parity test can assert the
/// committed file still matches the seed.
String buildEngineFixture() {
  final b = StringBuffer()
    ..writeln('// GENERATED by tool/gen_engine_fixture.dart — DO NOT EDIT BY HAND.')
    ..writeln('// Source of truth: lib/data/seed/catalog_seed.dart +')
    ..writeln('// lib/data/seed/plant_task_rules_seed.dart')
    ..writeln('// Regenerate: dart run tool/gen_engine_fixture.dart')
    ..writeln()
    ..writeln("import type { PlantTaskRule, TaskTypeMeta } from '../types.ts';")
    ..writeln()
    ..writeln('export const kTaskTypeRows: TaskTypeMeta[] = [');

  for (final t in CatalogSeed.taskTypes) {
    final labels = jsonEncode({'sl': t.sl, 'en': t.en, 'de': t.de});
    b.writeln(
      '  { id: ${_s(t.id)}, default_cadence: ${t.defaultCadence ?? 'null'}, '
      'weather_sensitive: ${t.weatherSensitive}, seasonal: ${t.seasonal}, '
      'labels: $labels },',
    );
  }

  b
    ..writeln('];')
    ..writeln()
    ..writeln('export const kPlantTaskRuleRows: PlantTaskRule[] = [');

  for (final r in PlantTaskRulesSeed.rules) {
    // `window` is already a JSON string in the seed; re-encode through decode so
    // the emitted literal is normalised (and malformed JSON fails the generator,
    // not the simulation).
    final window = jsonEncode(jsonDecode(r.window));
    b.writeln(
      '  { id: ${_s(r.id)}, scope: ${_s(r.scope)}, ref_id: ${_s(r.refId)}, '
      'task_type_id: ${_s(r.taskTypeId)}, timing_anchor: ${_s(r.timingAnchor)}, '
      'window: $window, frost_gate: ${r.frostGate}, '
      'weather_guard: ${_sOrNull(r.weatherGuard)}, '
      'message_key: ${_s(r.messageKey)} },',
    );
  }

  b.writeln('];');
  return b.toString();
}
