// Generates supabase/seed/catalog.sql from the single source of truth
// (lib/data/seed/catalog_seed.dart) so the cloud catalog never diverges from
// the app's seed. Idempotent upsert (on conflict ... do update) — safe to
// re-run after the seed grows/changes. Run: dart run tool/gen_catalog_sql.dart
//
// The cloud catalog is the source of truth that devices pull (M6.3); this tool
// only (re)materializes it from the Dart seed. IDs are stable by contract —
// see CLAUDE.md (catalog ids are add-only, never renamed).
import 'dart:convert';
import 'dart:io';

import 'package:tendask/data/seed/catalog_seed.dart';

String _q(String s) => "'${s.replaceAll("'", "''")}'";
String _jsonb(Map<String, String> m) => "${_q(jsonEncode(m))}::jsonb";

void main() {
  final out = File('supabase/seed/catalog.sql')
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(buildCatalogSql());
  stdout.writeln(
    'Wrote ${out.path}: ${CatalogSeed.taskTypes.length} task_type, '
    '${CatalogSeed.plants.length} plant, '
    '${CatalogSeed.categoryMatrix.length} category_task_type rows.',
  );
}

/// Builds the catalog SQL from the seed. Pure (no I/O) so a test can assert the
/// committed catalog.sql still matches the seed (cloud ⊇ every referenced id).
String buildCatalogSql() {
  final b = StringBuffer()
    ..writeln('-- GENERATED by tool/gen_catalog_sql.dart — DO NOT EDIT BY HAND.')
    ..writeln('-- Source of truth: lib/data/seed/catalog_seed.dart')
    ..writeln('-- Idempotent: re-run after seed changes, then apply to the cloud.')
    ..writeln();

  b.writeln('-- task_type');
  for (final t in CatalogSeed.taskTypes) {
    b.writeln(
      'insert into task_type '
      '(id, labels, icon, category, requires_subject, weather_sensitive, '
      'consumes_supplies, default_cadence) values ('
      '${_q(t.id)}, ${_jsonb({'sl': t.sl, 'en': t.en, 'de': t.de})}, '
      '${_q(t.icon)}, ${_q(t.category)}, ${t.requiresSubject}, '
      '${t.weatherSensitive}, ${t.consumesSupplies}, '
      '${t.defaultCadence ?? 'null'}) '
      'on conflict (id) do update set '
      'labels = excluded.labels, icon = excluded.icon, '
      'category = excluded.category, '
      'requires_subject = excluded.requires_subject, '
      'weather_sensitive = excluded.weather_sensitive, '
      'consumes_supplies = excluded.consumes_supplies, '
      'default_cadence = excluded.default_cadence;',
    );
  }

  b.writeln('\n-- plant');
  for (final p in CatalogSeed.plants) {
    final sci = p.scientificName == null ? 'null' : _q(p.scientificName!);
    b.writeln(
      'insert into plant (id, labels, scientific_name, category, icon) values ('
      '${_q(p.id)}, ${_jsonb({'sl': p.sl, 'en': p.en, 'de': p.de})}, '
      '$sci, ${_q(p.category)}, ${_q(p.icon)}) '
      'on conflict (id) do update set '
      'labels = excluded.labels, '
      'scientific_name = excluded.scientific_name, '
      'category = excluded.category, icon = excluded.icon;',
    );
  }

  b.writeln('\n-- category_task_type (plant category -> applicable task type)');
  for (final (category, taskTypeId) in CatalogSeed.categoryMatrix) {
    b.writeln(
      'insert into category_task_type (category, task_type_id) values '
      '(${_q(category)}, ${_q(taskTypeId)}) '
      'on conflict (category, task_type_id) do nothing;',
    );
  }

  return b.toString();
}
