// Generates supabase/functions/_shared/push_i18n.ts from lib/i18n/*.i18n.json.
// Extracts all nested keys whose leaf name is "title" under the "suggestions"
// top-level key, and builds a per-language title map for the FCM push sender.
// Run: dart run tool/gen_push_i18n.dart
//
// Re-run whenever suggestions.*.title keys are added or changed (e.g. in M11.13).
import 'dart:convert';
import 'dart:io';

void main() {
  final langs = ['en', 'sl', 'de'];
  // Map<lang, Map<messageKey, title>>
  final titles = <String, Map<String, String>>{};

  for (final lang in langs) {
    final file = File('lib/i18n/$lang.i18n.json');
    if (!file.existsSync()) {
      stderr.writeln('Warning: $lang.i18n.json not found — skipping');
      titles[lang] = {};
      continue;
    }
    final json = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
    final suggestions = json['suggestions'];
    if (suggestions is! Map<String, dynamic>) {
      titles[lang] = {};
      continue;
    }
    titles[lang] = _extractTitles(suggestions, 'suggestions');
  }

  final out = File('supabase/functions/_shared/push_i18n.ts').openWrite();
  out.writeln('// Generated by tool/gen_push_i18n.dart — do not edit manually.');
  out.writeln('// Re-run after adding/changing suggestions.*.title keys in lib/i18n/*.i18n.json.');
  out.writeln();
  out.writeln('const kTitles: Record<string, Record<string, string>> = {');
  for (final lang in langs) {
    out.write('  $lang: {');
    final map = titles[lang]!;
    if (map.isEmpty) {
      out.writeln('},');
    } else {
      out.writeln();
      for (final entry in map.entries) {
        final escaped = entry.value.replaceAll("'", r"\'");
        out.writeln("    '${entry.key}': '$escaped',");
      }
      out.writeln('  },');
    }
  }
  out.writeln('};');
  out.writeln();
  out.writeln("const kFallbackTitle: Record<string, string> = {");
  out.writeln("  en: 'Your garden needs attention',");
  out.writeln("  sl: 'Vaš vrt čaka na vas',");
  out.writeln("  de: 'Ihr Garten braucht Aufmerksamkeit',");
  out.writeln('};');
  out.writeln();
  out.writeln("const kFallbackBody: Record<string, string> = {");
  out.writeln("  en: 'Tap to see today\\'s suggestion',");
  out.writeln("  sl: 'Tapnite za predlog dneva',");
  out.writeln("  de: 'Tippen für den heutigen Vorschlag',");
  out.writeln('};');
  out.writeln();
  out.writeln('function norm(lang: string | null | undefined): string {');
  out.writeln("  return lang === 'sl' || lang === 'de' ? lang : 'en';");
  out.writeln('}');
  out.writeln();
  out.writeln(
    'export function pushTitle(messageKey: string, lang: string | null | undefined): string {',
  );
  out.writeln('  const l = norm(lang);');
  out.writeln('  return kTitles[l][messageKey] ?? kFallbackTitle[l];');
  out.writeln('}');
  out.writeln();
  out.writeln(
    'export function pushBody(lang: string | null | undefined): string {',
  );
  out.writeln('  return kFallbackBody[norm(lang)];');
  out.writeln('}');
  out.close();

  final count = titles.values.map((m) => m.length).fold(0, (a, b) => a + b);
  stdout.writeln(
    'push_i18n.ts generated: ${titles["en"]!.length} EN titles '
    '($count total across ${langs.length} langs)',
  );
}

/// Recursively collects keys where the leaf name is "title" under a
/// `suggestions.*` path, returning `Map<dotted.path, title>`.
Map<String, String> _extractTitles(Map<String, dynamic> node, String prefix) {
  final result = <String, String>{};
  for (final entry in node.entries) {
    final key = entry.key;
    final fullKey = '$prefix.$key';
    final value = entry.value;
    if (key == 'title' && value is String) {
      result[prefix] = value; // prefix = the suggestions.category.slug path
    } else if (value is Map<String, dynamic>) {
      result.addAll(_extractTitles(value, fullKey));
    }
  }
  return result;
}
