// Generates supabase/functions/_shared/push_i18n.ts from lib/i18n/*.i18n.json.
// Ships the push title of every message_key the engine can emit — the rules seed
// plus the three generic keys the rule code writes by hand — in all three
// languages, so the FCM sender never has to compose text.
// Run: dart run tool/gen_push_i18n.dart
//
// Re-run whenever suggestions.*.title or push.fallback_* change.
//
// Bodies are deliberately NOT shipped. A message body carries {subject},
// {frost_date}, {days_overdue} … which only the client can fill: it has the
// catalog labels, the user's own plant names and the locale's date format. The
// engine would have to reimplement all three, and the reader's plant names would
// travel through FCM for a line they see in full the moment they tap. So the
// push says the specific thing in its title and stays generic in its body — the
// decision is written up in docs/m11/03-pravila-r1-r7.md §Sporočila (P10.2).
import 'dart:convert';
import 'dart:io';

import 'seed/plant_task_rules_seed.dart';

void main() {
  File(
    'supabase/functions/_shared/push_i18n.ts',
  ).writeAsStringSync(buildPushI18n());
  stdout.writeln('push_i18n.ts generated');
}

/// The generated module as a string, so a test can compare it with the
/// committed file instead of trusting that someone re-ran the generator.
String buildPushI18n() {
  final langs = ['en', 'sl', 'de'];
  // Map<lang, Map<messageKey, title>>
  final titles = <String, Map<String, String>>{};
  final fallbackTitle = <String, String>{};
  final fallbackBody = <String, String>{};

  for (final lang in langs) {
    final file = File('lib/i18n/$lang.i18n.json');
    if (!file.existsSync()) {
      stderr.writeln('Warning: $lang.i18n.json not found — skipping');
      titles[lang] = {};
      continue;
    }
    final json = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
    titles[lang] = {
      for (final key in emittedMessageKeys) key: _title(json, key, lang),
    };
    fallbackTitle[lang] = _string(json, 'push.fallback_title', lang);
    fallbackBody[lang] = _string(json, 'push.fallback_body', lang);
  }

  final out = StringBuffer();
  out.writeln(
    '// Generated by tool/gen_push_i18n.dart — do not edit manually.',
  );
  out.writeln(
    '// Re-run after changing suggestions.*.title or push.fallback_* in lib/i18n/.',
  );
  out.writeln('//');
  out.writeln(
    '// Titles only, and only for keys the engine can emit. A suggestion *body*',
  );
  out.writeln(
    '// carries {subject}/{frost_date}/… which only the client can fill (catalog',
  );
  out.writeln(
    '// labels, the user\'s own plant names, the locale date format), so every push',
  );
  out.writeln(
    '// gets the generic body below — docs/m11/03-pravila-r1-r7.md §Sporočila.',
  );
  out.writeln();
  out.writeln('const kTitles: Record<string, Record<string, string>> = {');
  for (final lang in langs) {
    out.write('  $lang: {');
    final map = titles[lang]!;
    if (map.isEmpty) {
      out.writeln('},');
    } else {
      out.writeln();
      for (final entry in map.entries) {
        out.writeln("    '${entry.key}': '${_escape(entry.value)}',");
      }
      out.writeln('  },');
    }
  }
  out.writeln('};');
  out.writeln();
  out.writeln('const kFallbackTitle: Record<string, string> = {');
  for (final lang in langs) {
    out.writeln("  $lang: '${_escape(fallbackTitle[lang]!)}',");
  }
  out.writeln('};');
  out.writeln();
  out.writeln(
    '// Every push carries this body. See the header for why it is not',
  );
  out.writeln('// the suggestion body (P10.2).');
  out.writeln('const kFallbackBody: Record<string, string> = {');
  for (final lang in langs) {
    out.writeln("  $lang: '${_escape(fallbackBody[lang]!)}',");
  }
  out.writeln('};');
  out.writeln();
  out.writeln('function norm(lang: string | null | undefined): string {');
  out.writeln("  return lang === 'sl' || lang === 'de' ? lang : 'en';");
  out.writeln('}');
  out.writeln();
  out.writeln(
    'export function pushTitle(messageKey: string, lang: string | null | undefined): string {',
  );
  out.writeln('  const l = norm(lang);');
  out.writeln('  return kTitles[l][messageKey] ?? kFallbackTitle[l];');
  out.writeln('}');
  out.writeln();
  out.writeln(
    'export function pushBody(lang: string | null | undefined): string {',
  );
  out.writeln('  return kFallbackBody[norm(lang)];');
  out.writeln('}');
  out.writeln();
  out.writeln(
    '/** Every message_key with a title here, so a test can sweep all of them',
  );
  out.writeln(
    ' * through the marker filling instead of naming a lucky few. */',
  );
  out.writeln(
    'export const kPushMessageKeys: readonly string[] = Object.keys(kTitles.en);',
  );
  return out.toString();
}

/// Every message_key the engine can put on a suggestion: one per agronomy rule,
/// plus the three the rule code writes literally (R2 cadence, R3 anniversary,
/// R6 community). Harvesting `suggestions.*.title` instead swept up UI dialogs —
/// `done_sheet`, `remove` — that can never be a message_key, and would sweep up
/// the next one added (P10.2).
Set<String> get emittedMessageKeys => {
  for (final rule in PlantTaskRulesSeed.rules) rule.messageKey,
  'suggestions.cadence.overdue',
  'suggestions.history.anniversary',
  'suggestions.community.most_started',
};

String _escape(String s) => s.replaceAll("'", r"\'");

/// The `title` under a message_key path. A rule whose key has no catalog entry
/// would otherwise ship a push with the generic fallback in every language —
/// silently, which is how push_i18n.ts went stale once before.
String _title(Map<String, dynamic> root, String key, String lang) =>
    _string(root, '$key.title', lang);

String _string(Map<String, dynamic> root, String path, String lang) {
  dynamic node = root;
  for (final part in path.split('.')) {
    if (node is! Map<String, dynamic> || !node.containsKey(part)) {
      throw StateError('$lang.i18n.json has no $path');
    }
    node = node[part];
  }
  if (node is! String) {
    throw StateError('$lang.i18n.json $path is not a string');
  }
  return node;
}
